# docker-compose.yml
version: "2"
services:
  app:
    container_name: server_websocket_py
#    image: api_cayman:1.0
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py
#    volumes:
#      - /usr/local/volumes/fileserver/generarpdf/:/app/fileserver/
    ports:
      - "7667:7667"